version: 2.1
orbs:
  codecov: codecov/codecov@1.1.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: chmod +x gradlew && ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Building Project
          command: ./gradlew jar

      - run:
          name: Testing Project
          command: ./gradlew test
      - run:
          name: Jacoco Test Report
          command: ./gradlew jacocoTestReport
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

      # ========== 代码格式校验
      - run:
          name: Checkstyle Main
          command: ./gradlew checkstyleMain
      - run:
          name: Checkstyle Test
          command: ./gradlew checkstyleTest
      - run:
          name: Checkstyle Jmh
          command: ./gradlew checkstyleJmh
      # ========== 代码格式校验
      -
      - run:
          name: Shadow Jar
          command: ./gradlew shadowJar

      # ========== 上传代码覆盖报告
      - codecov/upload:
          file: build/jacoco/test.exec
      # ========== 上传代码覆盖报告
