version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build Project
          command: |
            chmod +x gradlew
            ./gradlew build
      - run:
          name: Jacoco Test Report
          command: ./gradlew jacocoTestReport
      # ========== 代码格式校验
      - run:
          name: Checkstyle Main
          command: ./gradlew checkstyleMain
      - run:
          name: Checkstyle Test
          command: ./gradlew checkstyleTest
      - run:
          name: Checkstyle Jmh
          command: ./gradlew checkstyleJmh
      # ========== 代码格式校验
      - run:
          name: Shadow Jar
          command: ./gradlew shadowJar
